### ISSUE TITLE
Error Install on Windows10 with Python 3.6.3

### ISSUE THREAD

**Issue by lzhbhlrPython** [Edinburgh-Genome-Foundry/pdf_reports#13]
I can't setup the package by pypi.
It's error msg:
```bash
    ERROR: Command errored out with exit status 1:
     command: 'd:\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-_0n1cb1k\\cairocffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-_0n1cb1k\\cairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-le1wnfc3'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-_0n1cb1k\cairocffi\
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-_0n1cb1k\cairocffi\setup.py", line 13, in <module>
        'cairocffi/ffi_build.py:ffi_pixbuf']
      File "d:\python36\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "d:\python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "d:\python36\lib\site-packages\setuptools\dist.py", line 426, in __init__
        k: v for k, v in attrs.items()
      File "d:\python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "d:\python36\lib\site-packages\setuptools\dist.py", line 717, in finalize_options
        ep(self)
      File "d:\python36\lib\site-packages\setuptools\dist.py", line 724, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "d:\python36\lib\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "d:\python36\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "d:\python36\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 28, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
    AttributeError: module 'constants' has no attribute '_CAIRO_HEADERS'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Please Help me!

**Comment by veghp** [comment]
Hi, did you manage to solve the issue? This seems to be a very similar problem to https://github.com/Edinburgh-Genome-Foundry/pdf_reports/issues/9, related to installation on Windows. I'll close this issue to avoid duplication. Unfortunately, this package wasn't tested on Windows and there are no plans for this in the future.
