### ISSUE TITLE
Error installing v0.3.2 with Python 3.7.7 on Windows

### ISSUE THREAD

**Issue by BrendanSimon** [Edinburgh-Genome-Foundry/pdf_reports#9]
I am trying to install pdf_reports v0.3.2 with Python 3.7.7 on Windows 10 Pro.

I've created a virtual env with:

```
 'C:\Program Files\Python37\python.exe' -m venv venv
```

Activated the venv with:

```
venv\Scripts\activate.ps1
```

Upgraded pip with:

```
python -m pip install -U pip
```

Tried to install `pdf_reports` with: 

```
pip install -U pdf_reports
```

The error message tail is:

```
Collecting cairocffi>=0.9.0
  Using cached cairocffi-1.1.0.tar.gz (68 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\brendan\my_report\sw\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\brend\\AppData\\Local\\Temp\\pip-install-6j9v_u0d\\cairocffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\brend\\AppData\\Local\\Temp\\pip-install-6j9v_u0d\\cairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\brend\AppData\Local\Temp\pip-pip-egg-info-8xm95usy'
         cwd: C:\Users\brend\AppData\Local\Temp\pip-install-6j9v_u0d\cairocffi\
    Complete output (24 lines):
    Download error on https://pypi.org/simple/pytest-runner/: _ssl.c:1059: The handshake operation timed out -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\brend\AppData\Local\Temp\pip-install-6j9v_u0d\cairocffi\setup.py", line 13, in <module>
        'cairocffi/ffi_build.py:ffi_pixbuf']
      File "d:\brendan\my_report\sw\venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "d:\brendan\my_report\sw\venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "d:\brendan\my_report\sw\venv\lib\site-packages\setuptools\dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "d:\brendan\my_report\sw\venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return installer(requirement)
      File "d:\brendan\m_report\sw\venv\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "d:\brendan\my_report\sw\venv\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by BrendanSimon** [comment]
Installed ok with Python 3.7.6 on macOS.

**Comment by BrendanSimon** [comment]
Hmmmm, it's working from MSYS2 terminal and from my PowerShell terminal ok, but not if I run it those shells from within a VS Code terminal.  That's strange as other modules seem to install ok.

Any ideas?

I'll keep going and see how I progress :)

**Comment by BrendanSimon** [comment]
It could be a path issue, at least with activating the python venv from within the VS Code terminal, as my PATH variable had a mixture of Windows and UNIX style paths.

**Comment by veghp** [comment]
Thank you for trying out pdf_reports -- did you manage to solve the issue? Unfortunately this package wasn't tested on Windows and there are no plans for this in the future.
